class CombatModule {
  constructor() { this.reset() }
  reset() {
    this.encounters=[]; this.current=null; this.lastZone=null; this.seq=0; this.entities=new Map(); this.incoming=new Map(); this.owners=new Map();
    this.participatingEnemies=new Set();
    this.maxEntityDamage=0; this.maxIncomingDamage=0; this.maxOwnerDamage=0; this.secondBuckets=new Map(); this.maxSecondDamage=0;
    this.playerName=null; this.petNames=new Set(); this.meterScope='everyone'; this.procs=[]; this.healing=new Map(); this.externalEncounter=null
  }
  setPlayerName(name){this.playerName=name?name.trim():null}
  claimPet(name){if(name)this.petNames.add(name.trim())}
  setMeterScope(scope){if(scope==='you'||scope==='everyone')this.meterScope=scope}
  setEncounterContext(external){this.externalEncounter=external||null}
  _syncEncounter(external, ts){
    if (!external) return
    if (this.current && external.status === 'completed' && this.current.status === 'active') {
      this.current.status='completed'; this.current.endTs=external.endTs||ts; this.current.duration=((this.current.endTs-this.current.startTs)/1000).toFixed(2)+'s'; this.current.endReason=external.endReason||null
    }
    if (external.status === 'active' && (!this.current || this.current._encId !== external.id)) {
      this.current={id:external.id,_encId:external.id,name:external.target||'Unknown',target:external.target||null,zone:external.zone||this.lastZone,startTs:external.startTs,status:'active',damage:0,hits:0,maxHit:0,duration:'0s',crits:0,misses:0,resists:0,healing:0,runes:0,absorbs:0,events:[]}
      this.encounters.unshift(this.current); if(this.encounters.length>50)this.encounters.pop()
      this._resetCombatMaps()
    }
  }
  _resetCombatMaps(){this.entities=new Map();this.incoming=new Map();this.owners=new Map();this.participatingEnemies=new Set();this.healing=new Map();this.maxEntityDamage=0;this.maxIncomingDamage=0;this.maxOwnerDamage=0;this.secondBuckets=new Map();this.maxSecondDamage=0;this.procs=[]}
  _classifyKind(name){if(!name)return'enemy';const n=name.toLowerCase();if((this.playerName&&n===this.playerName.toLowerCase())||n==='you'||n==='yourself')return'you';if(Array.from(this.petNames).some(p=>p.toLowerCase()===n))return'pet';return'enemy'}
  _scopeAllows(e){return this.meterScope==='everyone'||e.kind==='you'||e.owner==='You'||(this.playerName&&e.owner&&e.owner.toLowerCase()===this.playerName.toLowerCase())}
  _recordProc(ev,label,detail){this.procs.push({ts:ev.ts,seq:ev.seq,kind:ev.kind,label:label||ev.kind,detail:detail||''});if(this.procs.length>200)this.procs.shift()}
  _recordEvent(ev){if(!this.current||this.current.status!=='active')return;const e=this.current;e.events=e.events||[];e.events.push({ts:ev.ts,seq:ev.seq,kind:ev.kind,attacker:ev.attacker||null,target:ev.target||null,amount:ev.amount||null,dtype:ev.dtype||null,skill:ev.skill||ev.dclass||null,crit:!!ev.modifiers?.some(m=>/critical/i.test(m)),modifiers:ev.modifiers||[],mtype:ev.mtype||null,spell:ev.spell||null,verb:ev.verb||null,source:ev.source||null,owner:ev.owner||null,entityType:ev.entityType||null,overTime:!!ev.overTime});if(e.events.length>500)e.events.shift()}
  _ensureCurrent(ts){if(!this.current||this.current.status!=='active')this.current=this.startEncounter(ts,'Unknown');return this.current}
  _nameEncounter(enc,ev){const s=ev.target&&ev.target!=='You'&&ev.target!=='you'?ev.target:ev.attacker&&ev.attacker!=='You'&&ev.attacker!=='you'?ev.attacker:null;if(!s)return;if(!enc.target){enc.target=s;enc.name=enc.zone?`${enc.zone} — ${s}`:s}}
  _touchEntity(name,kind,owner,type){const k=name||'Unknown';let e=this.entities.get(k);if(!e)e={name:k,kind:kind||this._classifyKind(name),owner:owner||null,entityType:type||null,damage:0,hits:0,maxHit:0,deaths:0,crits:0,critDamage:0,categories:{melee:0,spell:0,dot:0,damageShield:0},skills:new Map()};if(owner)e.owner=owner;if(type)e.entityType=type;this.entities.set(k,e);return e}
  _touchOwner(owner){const k=owner||'Unknown';let e=this.owners.get(k);if(!e)e={name:k,kind:'owner',damage:0,hits:0,maxHit:0,crits:0,critDamage:0,categories:{melee:0,spell:0,dot:0,damageShield:0},skills:new Map()};this.owners.set(k,e);return e}
  _touchIncoming(name){const k=name||'Unknown';let e=this.incoming.get(k);if(!e)e={name:k,kind:'enemy',damage:0,hits:0,maxHit:0,critDamage:0,crits:0,categories:{melee:0,spell:0,dot:0,damageShield:0},skills:new Map()};this.incoming.set(k,e);return e}
  _touchHealing(name,owner,type){const k=name||'Unknown';let e=this.healing.get(k);if(!e)e={name:k,owner:owner||null,entityType:type||null,healing:0,casts:0,maxHeal:0,overTime:0};if(owner)e.owner=owner;if(type)e.entityType=type;this.healing.set(k,e);return e}
  _recordDamage(e,amount,dtype,skill,crit){if(!Number.isFinite(amount)||amount<0)return;const raw=String(dtype||'melee').toLowerCase();const c=raw==='ds'||raw==='damageshield'||raw==='damage_shield'?'damageShield':(raw==='dot'||raw==='damageovertime'||raw==='damage-over-time'?'dot':(raw==='spell'||raw==='magic'?'spell':(e.categories[raw]!==undefined?raw:'melee')));e.damage+=amount;e.hits++;e.maxHit=Math.max(e.maxHit,amount);e.categories[c]+=amount;if(crit){e.crits++;e.critDamage+=amount}if(skill){const s=e.skills.get(skill)||{name:skill,damage:0,hits:0,maxHit:0,category:c};s.damage+=amount;s.hits++;s.maxHit=Math.max(s.maxHit,amount);e.skills.set(skill,s)}}
  _updateMaxes(){this.maxEntityDamage=Math.max(0,...Array.from(this.entities.values()).map(e=>e.damage));this.maxIncomingDamage=Math.max(0,...Array.from(this.incoming.values()).map(e=>e.damage));this.maxOwnerDamage=Math.max(0,...Array.from(this.owners.values()).map(e=>e.damage))}
  _isPlayerTarget(name){return name==='You'||name==='you'||name==='yourself'||(this.playerName&&name?.toLowerCase()===this.playerName.toLowerCase())}
  _isLikelyGroupAttacker(ev){
    if (!ev.attacker || this._isPlayerTarget(ev.attacker) || this.petNames.has(ev.attacker)) return false
    // Damage directed at a non-player target is outgoing combat. If we have no
    // explicit pet/owner identity, treat the producer as an allied player.
    // Incoming damage is handled only when the target is the player.
    return !!ev.target && !this._isPlayerTarget(ev.target)
  }
  onEvent(ev,live){if(!live)return;this.seq=Math.max(this.seq,ev.seq||0);const external=this.externalEncounter;this._syncEncounter(external,ev.ts);switch(ev.kind){case'zone':this.lastZone=ev.zone;if(this.current?.status==='active'&&!external){this.current.status='completed';this.current.endTs=ev.ts;this.current.duration=((ev.ts-this.current.startTs)/1000).toFixed(0)+'s'}if(!external)this.current=this.startEncounter(ev.ts,ev.zone);this.current&&(this.current.zone=ev.zone);this._resetCombatMaps();break;
  case'damage':{const amount=Number(ev.amount);if(!Number.isFinite(amount))break;const enc=this._ensureCurrent(ev.ts);this._nameEncounter(enc,ev);const crit=!!ev.modifiers?.some(m=>/critical/i.test(m));const isPlayer=this._isPlayerTarget(ev.attacker);const explicitOwner=ev.owner||null;const inferredGroupPlayer=this._isLikelyGroupAttacker(ev);const owner=explicitOwner||(isPlayer?'You':(inferredGroupPlayer?ev.attacker:null));const kind=ev.entityType||(isPlayer?'you':(explicitOwner?'pet':(inferredGroupPlayer?'player':'enemy')));const ent=this._touchEntity(ev.attacker,kind,owner,ev.entityType);if(owner){enc.damage+=amount;enc.hits++;enc.maxHit=Math.max(enc.maxHit,amount);if(crit)enc.crits=(enc.crits||0)+1;this._recordDamage(ent,amount,ev.dtype,ev.skill||ev.dclass||ev.spell,crit);this._recordDamage(this._touchOwner(owner),amount,ev.dtype,ev.skill||ev.dclass||ev.spell,crit);const sec=Math.floor(ev.ts/1000),v=(this.secondBuckets.get(sec)||0)+amount;this.secondBuckets.set(sec,v);this.maxSecondDamage=Math.max(this.maxSecondDamage,v)}const targetPlayer=this._isPlayerTarget(ev.target);if(!owner&&targetPlayer){this.participatingEnemies.add(ev.attacker||'Unknown');this._recordDamage(this._touchIncoming(ev.attacker),amount,ev.dtype,ev.skill||ev.dclass||ev.spell,crit)}this._updateMaxes();this._recordEvent(ev);break}
  case'death':{const e=this._touchEntity(ev.target);e.deaths++;if(this.current?.status==='active'&&!external){this.current.status='completed';this.current.endTs=ev.ts;this.current.duration=((ev.ts-this.current.startTs)/1000).toFixed(0)+'s';this._nameEncounter(this.current,ev)}this._recordEvent(ev);break}
  case'playerDeath':{this._touchEntity('You','you','You').deaths++;if(this.current?.status==='active'&&!external){this.current.status='completed';this.current.endTs=ev.ts;this.current.duration=((ev.ts-this.current.startTs)/1000).toFixed(0)+'s';this._nameEncounter(this.current,ev)}this._recordEvent(ev);break}
  case'miss':{const enc=this._ensureCurrent(ev.ts);this._nameEncounter(enc,ev);if(this._isPlayerTarget(ev.attacker))enc.misses=(enc.misses||0)+1;if(ev.mtype&&ev.mtype!=='miss')this._recordProc(ev,ev.mtype,ev.verb?`(${ev.verb})`:'');this._recordEvent(ev);break}
  case'resist':{const enc=this._ensureCurrent(ev.ts);this._nameEncounter(enc,ev);if(this._isPlayerTarget(ev.caster))enc.resists=(enc.resists||0)+1;this._recordProc(ev,ev.partial?'partial resist':'full resist',ev.spell?`vs ${ev.spell}`:'');this._recordEvent(ev);break}
  case'heal':{const amount=Number(ev.amount)||0;const enc=this._ensureCurrent(ev.ts);this._nameEncounter(enc,ev);const healer=ev.healer||ev.caster||ev.source||null;const owner=ev.owner||(this._isPlayerTarget(healer)?'You':null);if(healer&&amount>0){const h=this._touchHealing(healer,owner,ev.entityType);h.healing+=amount;h.casts++;h.maxHeal=Math.max(h.maxHeal,amount);if(ev.overTime)h.overTime+=amount}if(owner)enc.healing=(enc.healing||0)+amount;this._recordEvent(ev);break}
  case'mitigation':{const enc=this._ensureCurrent(ev.ts);this._nameEncounter(enc,ev);if(ev.mtype==='rune'){enc.runes=(enc.runes||0)+(ev.amount||0);this._recordProc(ev,'rune',`absorbed ${ev.amount}`)}else{enc.absorbs=(enc.absorbs||0)+1;this._recordProc(ev,ev.mtype||'absorb','')}this._recordEvent(ev);break}
  case'proc':this._recordProc(ev,ev.spell||ev.name||'proc',ev.detail||'');this._recordEvent(ev);break;case'petClaim':this.claimPet(ev.name);break;default:this._recordEvent(ev)}}
  startEncounter(ts,name){const e={id:Date.now(),name:name||this.lastZone||'Unknown',target:null,zone:this.lastZone,startTs:ts,status:'active',damage:0,hits:0,maxHit:0,duration:'0s',crits:0,misses:0,resists:0,healing:0,runes:0,absorbs:0,events:[]};this.current=e;this.encounters.unshift(e);if(this.encounters.length>50)this.encounters.pop();this._resetCombatMaps();return e}
  _ser(e,secs,max){return{name:e.name,kind:e.kind,owner:e.owner||null,entityType:e.entityType||null,damage:e.damage,hits:e.hits,maxHit:e.maxHit,deaths:e.deaths||0,crits:e.crits,critDamage:e.critDamage,avgHit:e.hits?Math.round(e.damage/e.hits):0,dps:Math.floor(e.damage/secs),pct:max?(e.damage/max)*100:0,categories:{...e.categories},skills:Array.from(e.skills.values()).sort((a,b)=>b.damage-a.damage).slice(0,10).map(s=>({...s,pct:e.damage?(s.damage/e.damage)*100:0}))}}
  _serHealing(e,secs){return{name:e.name,owner:e.owner||null,entityType:e.entityType||null,healing:e.healing,casts:e.casts,maxHeal:e.maxHeal,avgHeal:e.casts?Math.round(e.healing/e.casts):0,hps:Math.floor(e.healing/secs),overTime:e.overTime}}
  snapshot(){const active=this.current?.status==='active',secs=active?Math.max(1,(Date.now()-this.current.startTs)/1000):1;const outgoingAll=Array.from(this.entities.values()).filter(e=>(e.kind==='you'||e.kind==='player'||e.kind==='pet'||e.kind==='charmed')&&this._scopeAllows(e)).sort((a,b)=>b.damage-a.damage);const outgoing=outgoingAll.slice(0,20).map(e=>this._ser(e,secs,this.maxEntityDamage));const owners=Array.from(this.owners.values()).sort((a,b)=>b.damage-a.damage).map(e=>this._ser(e,secs,this.maxOwnerDamage));const incoming=Array.from(this.incoming.values()).filter(e=>this.participatingEnemies.has(e.name)).sort((a,b)=>b.damage-a.damage).slice(0,20).map(e=>this._ser(e,secs,this.maxIncomingDamage));const healing=Array.from(this.healing.values()).sort((a,b)=>b.healing-a.healing).slice(0,20).map(e=>this._serHealing(e,secs));const totalOut=owners.reduce((s,e)=>s+e.damage,0),totalIn=incoming.reduce((s,e)=>s+e.damage,0),totalHealing=healing.reduce((s,e)=>s+e.healing,0);return{encounters:this.encounters,current:this.current,seq:this.seq,outgoing,owners,incoming,healing,totalOut,totalIn,totalHealing,allDamage:totalOut+totalIn,maxEntityDamage:this.maxEntityDamage,maxIncomingDamage:this.maxIncomingDamage,maxOwnerDamage:this.maxOwnerDamage,bestSec:this.maxSecondDamage,activeSecs:secs,procs:this.procs,participatingEnemies:Array.from(this.participatingEnemies),meter:{mode:'damageDealt',label:'DPS',currentTarget:this.current?.target||null,duration:this.current?.duration||'0s',dealt:{total:totalOut,rows:outgoing},taken:{total:totalIn,rows:incoming}}}}
}
module.exports={CombatModule}